### ISSUE TITLE
Changelog and versioning

### ISSUE THREAD

**Issue by pracucci** [grafana/cortex-jsonnet#159]
This project is not versioned and has no changelog. For a non Grafana user it's quite difficult to understand which `cortex-jsonnet` version should run for a specific Cortex version. For example, the jsonnet `master` doesn't necessarily run with the latest Cortex stable version, because of config breaking changes done in the meanwhile for experimental features (eg. blocks storage).

I would **propose** to:
1. Introduce a `CHANGELOG.md` for any user-facing change
2. Cut a new version of the mixin every time a stable Cortex version is cut and keep the same versioning number (eg. `cortex-jsonnet` `1.3.0` should be used to run Cortex `1.3.0`)

Thoughts?

**Comment by pstibrany** [comment]
100% agree. I would add:

* Changes to cortex-jsonnet master branch should reflect Cortex master. Since not everyone is running Cortex master, versioning would make this clearer.

**Comment by gouthamve** [comment]
+++++1 Yep! This is long overdue!
