### ISSUE TITLE
S3 Block Storage Support Incomplete

### ISSUE THREAD

**Issue by forestsword** [grafana/cortex-jsonnet#166]
Hi everyone! I'd like to be able to use the following config and get block storage using aws s3:

```
local cortex = import 'cortex/cortex.libsonnet';

cortex {
  _config+:: {
    namespace: 'default',

    storage_backend: 'aws',
    storage_engine: 'blocks'
    aws_region: 'us-east-1',
    s3_bucket_name: 'my-bucket',
    ruler_client_type: 's3',

    blocksStorageConfig: 'have to override',
  },
}
```

But the `blocksStorageConfig` is currently hardcoded to gcs:

https://github.com/grafana/cortex-jsonnet/blob/76e5ce31383ab88aee7311e5267b1e2a5516f62b/cortex/config.libsonnet#L144-L145

I'd expect the configs above to configure block storage for s3 correctly.

**Comment by pracucci** [comment]
We have an open PR to fix it https://github.com/grafana/cortex-jsonnet/pull/140 but it's not ready to merge yet. @forestsword would you like to check out my latest comments on #140 and pick it up from there? The remaining work should be quite small.
