### ISSUE TITLE
Consider attaching a build of the mixin with each release

### ISSUE THREAD

**Issue by jdbaldry** [grafana/cortex-jsonnet#245]
It would require any consumer to use the same label matchers that we do and anyone that wants control over these matchers still needs to buy into the Jsonnet tooling but it may be simpler for some use cases.

**Comment by pracucci** [comment]
If you can start writing a `RELEASE.md` instructions (including the building) we'll follow it to provide a build of the mixin during the next release. Typically the mixin is released by Cortex maintainers once a new Cortex version is out.

**Comment by jdbaldry** [comment]
Sure thing!
