### ISSUE TITLE
CortexQuerierHighRefetchRate will not fire

### ISSUE THREAD

**Issue by bboreham** [grafana/cortex-jsonnet#267]
This line:
https://github.com/grafana/cortex-jsonnet/blob/61afd56c9cb9879fe64fe15f4043aa5520f67468/cortex-mixin/alerts/blocks.libsonnet#L175

will fail with newer versions of the Prometheus client library that are OpenMetrics-compatible.
`"0"` is now written `"0.0"`.

Since nothing now matches that label, the query returns nothing and the alert will never fire.

**Comment by pracucci** [comment]
Thanks Bryan for spotting it! Does #268 looks good to you or is there a better way to fix it?

**Comment by bboreham** [comment]
I just changed it to `="0.0"` in my version.
