### ISSUE TITLE
cortex_ingester_active_series is not a valid metric/recording rule

### ISSUE THREAD

**Issue by friedrich-at-adobe** [grafana/cortex-jsonnet#320]
cortex_ingester_active_series used in write dashboard is not defined anywhere

https://github.com/grafana/cortex-jsonnet/blob/410f9fe540bc8d375097a0c0f975290d852514ef/cortex-mixin/dashboards/writes.libsonnet#L30

**Comment by pracucci** [comment]
The `cortex_ingester_active_series` is conditionally enabled when `-ingester.active-series-metrics-enabled=true`. We just had the Cortex community call (1h ago) and decided to flip the default value of that flag to true.
