### ISSUE TITLE
1.10 Release?

### ISSUE THREAD

**Issue by hamishforbes** [grafana/cortex-jsonnet#400]
Cortex 1.10 has been out for a wee while now, is there an intention to keep versioning consistent between the main Cortex project and this config repo?
Or would it be best to just pin my jsonnetfile to a newer commit now?

**Comment by pracucci** [comment]
Yes, we should but unfortunately we didn't yet. In the meanwhile, I think you could look for the latest commit (by time) before Cortex 1.10 was released. Picking that commit should be safe for Cortex 1.10.

**Comment by luna-duclos** [comment]
Wanting to second the request to create a tag! Its been months by now and thats a bit silly.

**Comment by hamishforbes** [comment]
FWIW i'm using the current latest head commit (1eb46b06d7af7c2090fab8d5e3b6b665d0b2fe8d) with 1.11 just fine

**Comment by pracucci** [comment]
I've just released:
- https://github.com/grafana/cortex-jsonnet/releases/tag/1.10.0
- https://github.com/grafana/cortex-jsonnet/releases/tag/1.11.0
