### ISSUE TITLE
Query ingesters within 12h too long?

### ISSUE THREAD

**Issue by weeco** [grafana/cortex-jsonnet#49]
I am not sure why it would make sense to set ` querier.query-ingesters-within` to 12h as shown here: https://github.com/grafana/cortex-jsonnet/blob/master/cortex/config.libsonnet#L149 .

As the comment says the ingesters store chunks 6h and the configured retain period is 15m (see https://github.com/grafana/cortex-jsonnet/blob/master/cortex/ingester.libsonnet#L21-L22). Doesn't that mean chunks can only live up to 6h15min in ingesters or is there something else to consider as well?

One might want to change this value or add a better comment why 12h is reasonable I think.

**Comment by tomwilkie** [comment]
This is indeed a good question - your reasoning makes sense.  Except it can take some time for the chunks to be flushed, and if [you look at our alerts](https://github.com/grafana/cortex-jsonnet/blob/master/cortex-mixin/alerts.libsonnet#L204) you'll see we sometimes see chunks take up to 10hrs to flush - so I suspect this is put in here to ensure users / customers never see gaps.  Gaps are bad as they will be cached in the frontend.

**Comment by weeco** [comment]
Thanks for the explanation.

Because I am curious: Do you happen to know why it takes that long sometimes? Is it because BigTable is not able to process that many write requests sometimes and hence there might be a queue of up to 4h or what's the reason that it takes so much longer sometimes?

**Comment by gouthamve** [comment]
Also, one more reason is that people can write some old data. Like
Prometheus writing to Cortex could be an hour or two behind for whatever
reason. This is just an extra-safe buffer in those cases.

Thanks,
Goutham.

**Comment by tomwilkie** [comment]
>  Is it because BigTable is not able to process that many write requests sometimes and hence there might be a queue of up to 4h or what's the reason that it takes so much longer sometimes?

I wouldn't characterise it like that - I'd say its more that users series churn is not always constant, so the number of chunks to flush is highly variable - and our bigtable is statically provisioned.
