### ISSUE TITLE
Lets add some CI that checks the readme instructions work

### ISSUE THREAD

**Issue by tomwilkie** [grafana/cortex-jsonnet#98]
Ie setup a tanka env, install the jsonnet bundle and do a `tk show`

**Comment by carlpett** [comment]
Probably a good idea - I just tested following the steps in the README and

```
evaluating jsonnet: RUNTIME ERROR: Field does not exist: spec
        /<PATH>/vendor/consul/consul.libsonnet:305:5-20
        During manifestation
```

**Comment by jdbaldry** [comment]
Hi @carlpett, sorry for the inconvenience! I'll bump this up my to do list and take a look soon

**Comment by jdbaldry** [comment]
@carlpett You may have already resolved this yourself but the error you are experiencing comes from some changes in a Kubernetes Jsonnet library we are using. Previously this library was the ksonnet `k.libsonnet` but with ksonnet no longer being maintained we have been steadily migrating to using a new library which is more consistent and is being continually maintained by members of the Jsonnet libs community. If you are interested, you can find more information at the library documentation page https://jsonnet-libs.github.io/k8s-alpha/1.14/
